/* =========================================================================
   BANCO DE QUESTÕES — estilo INSTITUTO AOCP (PMGO)
   -------------------------------------------------------------------------
   Formato: { id, materia, nivel, enunciado, alternativas[5], correta, explicacao }
   nivel: "facil" | "medio" | "dificil"
   Padrões da banca reproduzidos: 5 alternativas (A–E), comando negativo
   (INCORRETA/NÃO/EXCETO), casos concretos e assertivas de verdadeiro/falso.

   AVISO: conteúdo de estudo. Confira sempre a legislação vigente — leis mudam.
   ========================================================================= */

const QUESTIONS = [

  /* ===================================================================
     REALIDADE DE GOIÁS
     =================================================================== */
  { id: "go1", materia: "realidade_goias", nivel: "facil",
    enunciado: "A ocupação do território goiano no século XVIII foi impulsionada principalmente pela:",
    alternativas: ["Pecuária extensiva de exportação", "Mineração de ouro (bandeiras paulistas)", "Cultura cafeeira", "Construção de ferrovias", "Industrialização"],
    correta: 1,
    explicacao: "O povoamento de Goiás no séc. XVIII foi movido pela MINERAÇÃO DO OURO, via bandeiras paulistas (Anhanguera). Correta: B." },
  { id: "go2", materia: "realidade_goias", nivel: "medio",
    enunciado: "A Revolta de Trombas e Formoso (Goiás, anos 1950) caracteriza-se como movimento de:",
    alternativas: ["Independência separatista", "Resistência camponesa por posse da terra", "Greve de mineradores", "Revolta urbana estudantil", "Conflito religioso"],
    correta: 1,
    explicacao: "Foi um CONFLITO AGRÁRIO — resistência de posseiros/camponeses no norte goiano contra a grilagem. Correta: B." },
  { id: "go3", materia: "realidade_goias", nivel: "facil",
    enunciado: "O rio que corta a região metropolitana de Goiânia, cuja bacia foi cobrada na prova de 2022, é o:",
    alternativas: ["Rio Araguaia", "Rio Tocantins", "Rio Meia Ponte", "Rio Paranaíba", "Rio das Almas"],
    correta: 2,
    explicacao: "A Bacia do RIO MEIA PONTE atravessa Goiânia (Q11 do Combatente/2022). Correta: C." },
  { id: "go4", materia: "realidade_goias", nivel: "facil",
    enunciado: "A Chapada dos Veadeiros destaca-se no relevo goiano por:",
    alternativas: ["Ter a menor altitude do estado", "Concentrar os pontos de maior altitude de Goiás", "Ser planície litorânea", "Pertencer ao bioma Amazônico", "Estar abaixo do nível do mar"],
    correta: 1,
    explicacao: "Concentra os PONTOS DE MAIOR ALTITUDE de Goiás. Correta: B." },
  { id: "go5", materia: "realidade_goias", nivel: "medio",
    enunciado: "Sobre a Primeira República (República Velha) em Goiás, assinale a alternativa correta.",
    alternativas: ["O poder era exercido por oligarquias, com destaque para a família Caiado, e a ferrovia chegou em 1913.", "Não havia coronelismo, pois o estado era industrializado.", "Goiânia já era a capital desde 1900.", "Foi palco da Guerra dos Farrapos.", "A economia baseava-se na indústria automobilística."],
    correta: 0,
    explicacao: "Domínio OLIGÁRQUICO (família Caiado) e FERROVIA em 1913. Goiânia só seria capital em 1937. Correta: A." },
  { id: "go6", materia: "realidade_goias", nivel: "facil",
    enunciado: "Assinale a alternativa correta sobre a capital de Goiás.",
    alternativas: ["Goiânia é a capital desde a fundação do estado.", "A capital sempre foi Brasília.", "A antiga capital era a Cidade de Goiás (Vila Boa); Goiânia tornou-se capital em 1937.", "Anápolis é a atual capital.", "A capital foi transferida para Rio Verde em 1950."],
    correta: 2,
    explicacao: "A antiga capital era a CIDADE DE GOIÁS (Vila Boa); a transferência para GOIÂNIA ocorreu em 1937. Correta: C." },
  { id: "go7", materia: "realidade_goias", nivel: "facil",
    enunciado: "O bioma predominante no território de Goiás é o:",
    alternativas: ["Amazônia", "Caatinga", "Cerrado", "Pantanal", "Mata Atlântica"],
    correta: 2,
    explicacao: "Goiás está majoritariamente no bioma CERRADO, o segundo maior do Brasil. Correta: C." },
  { id: "go8", materia: "realidade_goias", nivel: "medio",
    enunciado: "O bandeirante associado à descoberta do ouro em Goiás e à fundação de Vila Boa é conhecido como:",
    alternativas: ["Domingos Jorge Velho", "Anhanguera (Bartolomeu Bueno da Silva)", "Fernão Dias Paes", "Raposo Tavares", "Borba Gato"],
    correta: 1,
    explicacao: "O ANHANGUERA (Bartolomeu Bueno da Silva, pai e filho) está ligado ao ouro goiano e a Vila Boa. Correta: B." },
  { id: "go9", materia: "realidade_goias", nivel: "medio",
    enunciado: "Sobre a construção de Goiânia, é correto afirmar que:",
    alternativas: ["Foi uma cidade planejada, inaugurada na década de 1930, para ser a nova capital.", "Surgiu espontaneamente no século XVIII com a mineração.", "Foi construída por portugueses no período colonial.", "É a cidade mais antiga do estado.", "Foi planejada por Oscar Niemeyer como capital federal."],
    correta: 0,
    explicacao: "Goiânia foi CIDADE PLANEJADA (Pedro Ludovico Teixeira), inaugurada nos anos 1930, para substituir a Cidade de Goiás como capital. Correta: A." },
  { id: "go10", materia: "realidade_goias", nivel: "dificil",
    enunciado: "Sobre a economia colonial de Goiás, assinale a alternativa INCORRETA.",
    alternativas: ["A mineração do ouro foi a principal atividade no séc. XVIII.", "Com a decadência do ouro, a pecuária ganhou importância.", "A mão de obra escravizada foi amplamente utilizada nas minas.", "A economia colonial goiana baseou-se na indústria têxtil.", "O declínio da mineração levou a um período de estagnação econômica."],
    correta: 3,
    explicacao: "Comando NEGATIVO. NÃO havia indústria têxtil na colônia — a base era mineração e depois pecuária. Correta: D." },
  { id: "go11", materia: "realidade_goias", nivel: "medio",
    enunciado: "Entre os povos indígenas historicamente presentes no território goiano, destacam-se os:",
    alternativas: ["Ianomâmis e Tikunas", "Xavantes, Karajás e Avá-Canoeiro", "Guaranis e Kaingangs", "Tupinambás do litoral", "Incas"],
    correta: 1,
    explicacao: "Goiás abriga povos como Karajá, Avá-Canoeiro e, na região, os Xavante. Correta: B." },
  { id: "go12", materia: "realidade_goias", nivel: "facil",
    enunciado: "A antiga capital de Goiás, tombada como Patrimônio Histórico pela UNESCO, é:",
    alternativas: ["Pirenópolis", "Cidade de Goiás (Goiás Velho)", "Anápolis", "Catalão", "Jataí"],
    correta: 1,
    explicacao: "A Cidade de Goiás (Goiás Velho / Vila Boa) é Patrimônio Cultural da Humanidade pela UNESCO. Correta: B." },
  { id: "go13", materia: "realidade_goias", nivel: "medio",
    enunciado: "Economicamente, Goiás destaca-se hoje, sobretudo, pela:",
    alternativas: ["Indústria naval", "Agropecuária e agroindústria (grãos, carne, sucroenergético)", "Extração de petróleo offshore", "Turismo de praia", "Mineração de ferro para exportação"],
    correta: 1,
    explicacao: "A economia goiana é fortemente baseada em AGROPECUÁRIA e AGROINDÚSTRIA. Correta: B." },
  { id: "go14", materia: "realidade_goias", nivel: "dificil",
    enunciado: "Sobre a hidrografia de Goiás, analise: I. O rio Araguaia faz divisa a oeste. II. O rio Meia Ponte corta Goiânia. III. Goiás situa-se em áreas de nascentes importantes (dispersor de águas). Está(ão) correta(s):",
    alternativas: ["Apenas I", "Apenas II", "Apenas I e III", "Apenas II e III", "I, II e III"],
    correta: 4,
    explicacao: "As três estão corretas: Araguaia a oeste, Meia Ponte em Goiânia, e Goiás é área de nascentes (planalto central). Correta: E." },
  { id: "go15", materia: "realidade_goias", nivel: "facil",
    enunciado: "A transferência da capital de Goiás, na década de 1930, esteve associada ao governo de:",
    alternativas: ["Juscelino Kubitschek", "Pedro Ludovico Teixeira", "Getúlio Vargas diretamente", "Ronaldo Caiado", "Mauro Borges"],
    correta: 1,
    explicacao: "PEDRO LUDOVICO TEIXEIRA, interventor de Goiás, liderou a mudança para Goiânia. Correta: B." },
  { id: "go16", materia: "realidade_goias", nivel: "medio",
    enunciado: "O clima predominante no estado de Goiás é classificado como:",
    alternativas: ["Equatorial úmido o ano todo", "Tropical, com estação seca (inverno) e chuvosa (verão)", "Semiárido", "Subtropical", "Frio de montanha"],
    correta: 1,
    explicacao: "Clima TROPICAL com duas estações bem definidas: seca (inverno) e chuvosa (verão) — típico do Cerrado. Correta: B." },

  /* ===================================================================
     DIREITO PENAL MILITAR (CPM — DL 1.001/69)
     =================================================================== */
  { id: "pm1", materia: "penal_militar", nivel: "medio",
    enunciado: "Quanto ao LUGAR do crime, o Direito Penal (comum e militar) adota a teoria da:",
    alternativas: ["Atividade", "Resultado", "Ubiquidade (mista)", "Intenção", "Representação"],
    correta: 2,
    explicacao: "Para o LUGAR do crime adota-se a UBIQUIDADE (mista): local da ação/omissão E onde se produziu o resultado. Correta: C." },
  { id: "pm2", materia: "penal_militar", nivel: "medio",
    enunciado: "Segundo o CPM, o crime de DESERÇÃO consuma-se, em regra, quando a ausência do serviço se prolonga por período superior a:",
    alternativas: ["24 horas", "3 dias", "5 dias", "8 dias", "15 dias"],
    correta: 3,
    explicacao: "A deserção (art. 187 do CPM) consuma-se após decorridos OITO DIAS (prazo de graça). Correta: D." },
  { id: "pm3", materia: "penal_militar", nivel: "dificil",
    enunciado: "Sobre as penas no Código Penal Militar, assinale a alternativa INCORRETA.",
    alternativas: ["A pena de morte é prevista apenas para crimes de tempo de guerra.", "O impedimento é uma das penas principais.", "A pena de morte é executada por fuzilamento.", "A pena de morte pode ser aplicada livremente em tempo de paz.", "A reforma pode figurar como pena acessória."],
    correta: 3,
    explicacao: "Comando NEGATIVO. Pena de morte só em TEMPO DE GUERRA — nunca em tempo de paz. Correta: D." },
  { id: "pm4", materia: "penal_militar", nivel: "medio",
    enunciado: "O crime de MOTIM no CPM caracteriza-se por:",
    alternativas: ["Militar isoladamente desobedecer ordem superior.", "Reunião de militares agindo contra a ordem/disciplina, recusando obediência ou praticando violência.", "Ausência do serviço por mais de 8 dias.", "Abandono de posto por sentinela.", "Deixar de cumprir horário isoladamente."],
    correta: 1,
    explicacao: "MOTIM (art. 149) exige CONCURSO DE MILITARES reunidos contra a ordem, disciplina ou autoridade. Correta: B." },
  { id: "pm5", materia: "penal_militar", nivel: "medio",
    enunciado: "Quanto ao TEMPO do crime, o CPM adota a teoria da:",
    alternativas: ["Ubiquidade", "Atividade (momento da ação ou omissão)", "Resultado", "Intercorrência", "Representação"],
    correta: 1,
    explicacao: "TEMPO do crime = teoria da ATIVIDADE (momento da conduta), ainda que o resultado ocorra em outro momento. Correta: B." },
  { id: "pm6", materia: "penal_militar", nivel: "facil",
    enunciado: "Apresentar-se ou permanecer embriagado em serviço configura, no CPM:",
    alternativas: ["Fato atípico", "Embriaguez em serviço (art. 202)", "Deserção", "Motim", "Peculato"],
    correta: 1,
    explicacao: "É o crime de EMBRIAGUEZ EM SERVIÇO (art. 202 do CPM). Correta: B." },
  { id: "pm7", materia: "penal_militar", nivel: "medio",
    enunciado: "Sobre o crime militar, é correto afirmar que:",
    alternativas: ["É apenas o praticado por civil.", "É definido em lei (critério ratione legis), abrangendo condutas do CPM em tempo de paz e de guerra.", "Não existe em tempo de paz.", "É sempre julgado pela Justiça comum.", "Depende de autorização do comandante para existir."],
    correta: 1,
    explicacao: "Crime militar é o DEFINIDO EM LEI (CPM), existindo em tempo de paz (art. 9º) e de guerra (art. 10). Correta: B." },
  { id: "pm8", materia: "penal_militar", nivel: "dificil",
    enunciado: "Analise as penas principais do CPM: I. Morte. II. Reclusão. III. Impedimento. IV. Multa como pena principal autônoma para todos os crimes. Estão corretas:",
    alternativas: ["Apenas I e II", "Apenas I, II e III", "Apenas III e IV", "Apenas II e IV", "I, II, III e IV"],
    correta: 1,
    explicacao: "São penas principais: morte, reclusão, detenção, prisão, impedimento, suspensão do exercício do posto e reforma. A multa NÃO é pena principal geral no CPM (diferente do CP comum). Corretas: I, II e III. Correta: B." },
  { id: "pm9", materia: "penal_militar", nivel: "medio",
    enunciado: "A pena de IMPEDIMENTO no CPM consiste, em síntese, em:",
    alternativas: ["Exclusão definitiva das forças armadas.", "Permanência do condenado na unidade, sem prejuízo da instrução, privado da liberdade de ir a lugares que a excedam.", "Pena pecuniária.", "Perda do posto e patente.", "Prisão em presídio comum."],
    correta: 1,
    explicacao: "O IMPEDIMENTO obriga o condenado a permanecer na unidade, sem ir além de seus limites, sem prejuízo da instrução militar. Correta: B." },
  { id: "pm10", materia: "penal_militar", nivel: "facil",
    enunciado: "Aplica-se a lei penal militar, em regra, ao crime cometido:",
    alternativas: ["Somente fora do país", "No território nacional ou a bordo de navios/aeronaves militares, observados os casos legais", "Apenas por civis", "Somente em tempo de guerra", "Somente contra o patrimônio"],
    correta: 1,
    explicacao: "A lei penal militar tem aplicação territorial, alcançando também navios e aeronaves militares, nos casos do CPM. Correta: B." },
  { id: "pm11", materia: "penal_militar", nivel: "dificil",
    enunciado: "Sobre a deserção, assinale a INCORRETA.",
    alternativas: ["Consuma-se após 8 dias de ausência.", "É crime propriamente militar.", "O oficial desertor pode ser agregado.", "Basta 1 dia de ausência para consumar a deserção.", "Existe processo especial de deserção no CPPM."],
    correta: 3,
    explicacao: "Comando NEGATIVO. NÃO basta 1 dia — exige MAIS DE 8 DIAS. Correta: D." },
  { id: "pm12", materia: "penal_militar", nivel: "medio",
    enunciado: "O militar que se apropria de dinheiro público de que tem a posse em razão do cargo pratica:",
    alternativas: ["Furto", "Peculato", "Estelionato", "Concussão", "Corrupção passiva"],
    correta: 1,
    explicacao: "Apropriar-se de valor de que se tem posse em razão do cargo = PECULATO (previsto também no CPM). Correta: B." },
  { id: "pm13", materia: "penal_militar", nivel: "facil",
    enunciado: "São bases constitucionais das instituições militares:",
    alternativas: ["Autonomia e independência", "Hierarquia e disciplina", "Colegialidade e consenso", "Liberdade e igualdade", "Mérito e antiguidade"],
    correta: 1,
    explicacao: "HIERARQUIA e DISCIPLINA são as bases das forças militares (art. 42 c/c 142 da CF). Correta: B." },
  { id: "pm14", materia: "penal_militar", nivel: "medio",
    enunciado: "A imputabilidade penal militar, quanto ao menor de 18 anos:",
    alternativas: ["Existe normalmente, respondendo como adulto.", "É afastada — menores de 18 anos são inimputáveis, sujeitos à legislação especial.", "Depende da patente.", "Só é afastada em tempo de guerra.", "Não é tratada no CPM."],
    correta: 1,
    explicacao: "Menores de 18 anos são INIMPUTÁVEIS, sujeitos à legislação especial (art. 228 CF; ECA). Correta: B." },
  { id: "pm15", materia: "penal_militar", nivel: "dificil",
    enunciado: "Sobre crimes militares em tempo de guerra, é correto afirmar que:",
    alternativas: ["Não existem no CPM.", "O CPM prevê tipos e penas específicos, inclusive a pena de morte.", "São julgados pela Justiça Eleitoral.", "Aplicam-se apenas a civis.", "Foram revogados pela CF/88."],
    correta: 1,
    explicacao: "O CPM traz LIVRO PRÓPRIO de crimes em tempo de guerra, com penas específicas, inclusive a de morte. Correta: B." },
  { id: "pm16", materia: "penal_militar", nivel: "medio",
    enunciado: "Recusar obediência a ordem de superior sobre matéria de serviço configura, em regra:",
    alternativas: ["Deserção", "Insubordinação/recusa de obediência", "Peculato", "Motim", "Abandono de posto"],
    correta: 1,
    explicacao: "A recusa de obediência a ordem legítima de superior é crime militar de INSUBORDINAÇÃO (recusa de obediência, art. 163). Correta: B." },

  /* ===================================================================
     DIREITO PROCESSUAL PENAL MILITAR (CPPM — DL 1.002/69)
     =================================================================== */
  { id: "ppm1", materia: "proc_penal_militar", nivel: "medio",
    enunciado: "O Inquérito Policial Militar (IPM) é presidido por:",
    alternativas: ["Delegado de polícia civil", "Oficial designado (autoridade de polícia judiciária militar)", "Promotor de Justiça", "Juiz de Direito", "Qualquer praça de serviço"],
    correta: 1,
    explicacao: "O IPM é da POLÍCIA JUDICIÁRIA MILITAR, presidido por OFICIAL designado. Correta: B." },
  { id: "ppm2", materia: "proc_penal_militar", nivel: "medio",
    enunciado: "No Processo Penal Militar, a MENAGEM é:",
    alternativas: ["Modalidade de pena principal", "Espécie de flagrante", "Medida que permite ao acusado permanecer em local determinado (quartel, cidade) durante o processo", "Recurso contra a sentença", "A denúncia do MP militar"],
    correta: 2,
    explicacao: "A MENAGEM é custódia branda: recolhimento a local determinado (quartel, residência, cidade). Correta: C." },
  { id: "ppm3", materia: "proc_penal_militar", nivel: "dificil",
    enunciado: "Sobre a competência da Justiça Militar Estadual, assinale a INCORRETA.",
    alternativas: ["Julga militares dos Estados nos crimes militares definidos em lei.", "Crime doloso contra a vida de civil por militar estadual vai ao Tribunal do Júri.", "A Justiça Militar Estadual julga civis pelos crimes comuns.", "Julga ações judiciais contra atos disciplinares militares.", "Compõe-se, em 1º grau, de juiz de direito e conselhos de justiça."],
    correta: 2,
    explicacao: "Comando NEGATIVO. A Justiça Militar ESTADUAL NÃO julga civis (diferente da federal). Correta: C." },
  { id: "ppm4", materia: "proc_penal_militar", nivel: "medio",
    enunciado: "O prazo para conclusão do IPM, estando o indiciado PRESO, é, em regra, de:",
    alternativas: ["10 dias", "15 dias", "20 dias", "30 dias", "40 dias"],
    correta: 2,
    explicacao: "IPM: 20 dias se o indiciado estiver PRESO; 40 dias se solto (prorrogável). Correta: C." },
  { id: "ppm5", materia: "proc_penal_militar", nivel: "medio",
    enunciado: "A ação penal militar, em regra, é:",
    alternativas: ["Privada", "Pública incondicionada, promovida pelo Ministério Público", "Popular", "Pública condicionada à representação do ofendido", "De iniciativa do comandante"],
    correta: 1,
    explicacao: "A ação penal militar é PÚBLICA INCONDICIONADA, titularidade do MP (art. 121 CPPM). Correta: B." },
  { id: "ppm6", materia: "proc_penal_militar", nivel: "facil",
    enunciado: "A peça que instaura a ação penal militar, oferecida pelo MP, denomina-se:",
    alternativas: ["Portaria", "Queixa-crime", "Denúncia", "Representação", "Requisição"],
    correta: 2,
    explicacao: "A DENÚNCIA é a peça do MP que instaura a ação penal pública militar. Correta: C." },
  { id: "ppm7", materia: "proc_penal_militar", nivel: "medio",
    enunciado: "O IPM tem natureza:",
    alternativas: ["Jurisdicional e contraditória", "Administrativa, inquisitiva e preparatória da ação penal", "Executória", "Recursal", "Legislativa"],
    correta: 1,
    explicacao: "O IPM é procedimento ADMINISTRATIVO, INQUISITIVO e PREPARATÓRIO (peça informativa). Correta: B." },
  { id: "ppm8", materia: "proc_penal_militar", nivel: "dificil",
    enunciado: "Sobre o processo especial de deserção, assinale a INCORRETA.",
    alternativas: ["É previsto no CPPM.", "Aplica-se ao crime de deserção.", "Envolve termo de deserção e agregação do oficial.", "Segue exatamente o rito comum, sem qualquer especialidade.", "Tem regras próprias de contagem de prazos."],
    correta: 3,
    explicacao: "Comando NEGATIVO. Justamente por ser ESPECIAL, não segue o rito comum. Correta: D." },
  { id: "ppm9", materia: "proc_penal_militar", nivel: "medio",
    enunciado: "A polícia judiciária militar pode ser exercida, entre outros, por:",
    alternativas: ["Qualquer cidadão", "Comandantes/autoridades militares e oficiais por delegação", "Somente pelo juiz auditor", "Promotor de justiça", "Delegado da Polícia Federal"],
    correta: 1,
    explicacao: "A polícia judiciária militar cabe às autoridades militares (comandantes) e oficiais por delegação (art. 7º CPPM). Correta: B." },
  { id: "ppm10", materia: "proc_penal_militar", nivel: "facil",
    enunciado: "O documento que dá início ao IPM, expedido pela autoridade militar, é a:",
    alternativas: ["Sentença", "Portaria", "Apelação", "Denúncia", "Menagem"],
    correta: 1,
    explicacao: "O IPM se inicia por PORTARIA da autoridade de polícia judiciária militar. Correta: B." },
  { id: "ppm11", materia: "proc_penal_militar", nivel: "dificil",
    enunciado: "Sobre nulidades e provas no CPPM, é correto afirmar que:",
    alternativas: ["Toda irregularidade gera nulidade absoluta automática.", "Vigora, em regra, o princípio de que não há nulidade sem prejuízo (pas de nullité sans grief).", "É vedada a produção de qualquer prova pericial.", "A confissão é a rainha das provas e vincula o juiz.", "Não existe sistema de recursos."],
    correta: 1,
    explicacao: "Aplica-se o princípio 'pas de nullité sans grief' — sem prejuízo não se declara a nulidade. Correta: B." },
  { id: "ppm12", materia: "proc_penal_militar", nivel: "medio",
    enunciado: "O Conselho de Justiça, órgão de 1º grau da Justiça Militar, é composto, em regra, por:",
    alternativas: ["Apenas juízes togados", "Juiz de direito (togado) e oficiais militares (juízes militares)", "Apenas oficiais generais", "Jurados populares", "Promotores e defensores"],
    correta: 1,
    explicacao: "Os Conselhos de Justiça reúnem o JUIZ togado e OFICIAIS militares (escabinato). Correta: B." },

  /* ===================================================================
     LEGISLAÇÃO EXTRAVAGANTE
     =================================================================== */
  { id: "leg1", materia: "legislacao", nivel: "medio",
    enunciado: "Na Lei de Drogas (11.343/2006), o 'tráfico privilegiado' (art. 33, §4º) exige que o agente seja:",
    alternativas: ["Reincidente específico", "Primário, de bons antecedentes, não dedicado a atividades criminosas nem integrante de organização criminosa", "Comerciante de grande quantidade", "Portador de arma", "Praticante do crime perto de escola"],
    correta: 1,
    explicacao: "Requisitos CUMULATIVOS: primário + bons antecedentes + não se dedicar ao crime + não integrar organização. Reduz 1/6 a 2/3. Correta: B." },
  { id: "leg2", materia: "legislacao", nivel: "facil",
    enunciado: "Manter arma de fogo de uso permitido em casa, sem registro, configura, no Estatuto do Desarmamento:",
    alternativas: ["Porte ilegal de arma", "Posse irregular de arma de fogo de uso permitido", "Comércio ilegal", "Tráfico internacional de arma", "Fato atípico"],
    correta: 1,
    explicacao: "Guardar/manter em RESIDÊNCIA ou trabalho = POSSE (art. 12). PORTE é fora desses locais (art. 14). Correta: B." },
  { id: "leg3", materia: "legislacao", nivel: "medio",
    enunciado: "Consideram-se infrações de MENOR potencial ofensivo (Lei 9.099/95) as contravenções e crimes com pena máxima:",
    alternativas: ["Não superior a 1 ano", "Não superior a 2 anos", "Não superior a 4 anos", "Não superior a 6 anos", "De qualquer quantidade"],
    correta: 1,
    explicacao: "IMPO = contravenções + crimes com pena máxima NÃO superior a 2 ANOS (art. 61). Correta: B." },
  { id: "leg4", materia: "legislacao", nivel: "dificil",
    enunciado: "Sobre a Lei Maria da Penha (11.340/2006), assinale a INCORRETA.",
    alternativas: ["Aplica-se à violência doméstica e familiar contra a mulher.", "Veda a aplicação da Lei 9.099/95 aos crimes por ela abrangidos.", "A lesão corporal em contexto doméstico é ação pública incondicionada (STF).", "Prevê medidas protetivas de urgência.", "Admite substituição da pena por cesta básica ou multa isolada."],
    correta: 4,
    explicacao: "Comando NEGATIVO. O art. 17 VEDA cesta básica e multa isolada. Correta: E." },
  { id: "leg5", materia: "legislacao", nivel: "medio",
    enunciado: "São equiparados a crimes hediondos, por previsão constitucional (art. 5º, XLIII):",
    alternativas: ["Furto, roubo e estelionato", "Tráfico de drogas, tortura e terrorismo", "Peculato e corrupção", "Homicídio culposo", "Dano e ameaça"],
    correta: 1,
    explicacao: "Os 'três T' equiparados: Tráfico, Tortura e Terrorismo (art. 5º, XLIII, CF). Correta: B." },
  { id: "leg6", materia: "legislacao", nivel: "medio",
    enunciado: "Quem porta droga para consumo pessoal (art. 28 da Lei de Drogas) está sujeito, entre outras, à pena de:",
    alternativas: ["Reclusão de 5 a 15 anos", "Advertência, prestação de serviços à comunidade e medida educativa (sem prisão)", "Prisão simples de 6 meses", "Multa de 10 salários mínimos apenas", "Detenção de 2 anos"],
    correta: 1,
    explicacao: "O usuário (art. 28) NÃO é preso: advertência, prestação de serviços e medida educativa. Correta: B." },
  { id: "leg7", materia: "legislacao", nivel: "facil",
    enunciado: "O Estatuto da Criança e do Adolescente (Lei 8.069/90) considera CRIANÇA a pessoa até:",
    alternativas: ["10 anos incompletos", "12 anos incompletos", "14 anos incompletos", "16 anos incompletos", "18 anos incompletos"],
    correta: 1,
    explicacao: "ECA: criança até 12 anos INCOMPLETOS; adolescente entre 12 e 18 anos. Correta: B." },
  { id: "leg8", materia: "legislacao", nivel: "dificil",
    enunciado: "Sobre a Lei de Crimes Ambientais (9.605/98), assinale a alternativa correta.",
    alternativas: ["A pessoa jurídica não pode ser responsabilizada penalmente.", "Admite responsabilidade penal da pessoa jurídica nos crimes ambientais.", "Só pune pessoas físicas maiores de 21 anos.", "Não prevê penas restritivas de direitos.", "Revogou o Código Penal."],
    correta: 1,
    explicacao: "A Lei 9.605/98 admite RESPONSABILIDADE PENAL DA PESSOA JURÍDICA em crimes ambientais (art. 3º). Correta: B." },
  { id: "leg9", materia: "legislacao", nivel: "medio",
    enunciado: "No JECrim, a proposta de aplicação imediata de pena restritiva ou multa, antes do processo, chama-se:",
    alternativas: ["Suspensão condicional do processo", "Transação penal", "Delação premiada", "Sursis da pena", "Livramento condicional"],
    correta: 1,
    explicacao: "A TRANSAÇÃO PENAL (art. 76) é o acordo para aplicação imediata de pena não privativa de liberdade nas IMPO. Correta: B." },
  { id: "leg10", materia: "legislacao", nivel: "medio",
    enunciado: "A suspensão condicional do processo (art. 89 da Lei 9.099/95) é cabível para crimes cuja pena MÍNIMA:",
    alternativas: ["Não seja superior a 1 ano", "Não seja superior a 2 anos", "Seja superior a 4 anos", "Seja de qualquer valor", "Não seja superior a 6 meses"],
    correta: 0,
    explicacao: "Sursis processual: pena MÍNIMA não superior a 1 ANO (art. 89). Correta: A." },
  { id: "leg11", materia: "legislacao", nivel: "dificil",
    enunciado: "Sobre a Lei de Drogas, assinale a INCORRETA.",
    alternativas: ["O tráfico é equiparado a hediondo.", "O usuário não é punido com pena privativa de liberdade.", "O tráfico privilegiado permite redução de pena.", "A associação para o tráfico é o mesmo que integrar organização criminosa da Lei 12.850.", "Financiar o tráfico é crime autônomo."],
    correta: 3,
    explicacao: "Comando NEGATIVO. Associação para o tráfico (art. 35) NÃO se confunde com organização criminosa (Lei 12.850/13) — são tipos distintos. Correta: D." },
  { id: "leg12", materia: "legislacao", nivel: "facil",
    enunciado: "O porte de arma de fogo de uso RESTRITO, em regra, é crime:",
    alternativas: ["De menor potencial ofensivo", "Equiparado a hediondo (art. 1º da Lei 8.072/90)", "Contravenção penal", "Atípico", "Punido só com multa"],
    correta: 1,
    explicacao: "Posse/porte de arma de uso restrito (art. 16) está no rol equiparado a hediondo. Correta: B." },
  { id: "leg13", materia: "legislacao", nivel: "medio",
    enunciado: "A Lei de Tortura (9.455/97) prevê como efeito da condenação, para o servidor público:",
    alternativas: ["Apenas multa", "Perda do cargo, função ou emprego público e interdição para seu exercício", "Advertência verbal", "Suspensão por 30 dias", "Nenhum efeito"],
    correta: 1,
    explicacao: "A condenação por tortura acarreta a PERDA DO CARGO e interdição pelo dobro do prazo da pena. Correta: B." },
  { id: "leg14", materia: "legislacao", nivel: "medio",
    enunciado: "(CFO) O Estatuto dos Policiais Militares de Goiás corresponde à Lei estadual:",
    alternativas: ["Lei 15.704/2006", "Lei 8.033/1975", "Lei 13.800/2001", "Lei 17.866/2012", "Lei 23.389/2025"],
    correta: 1,
    explicacao: "O Estatuto dos PM de Goiás é a Lei estadual 8.033/1975 (caiu 2x na prova de Cadete). Correta: B." },
  { id: "leg15", materia: "legislacao", nivel: "dificil",
    enunciado: "Sobre crimes hediondos (Lei 8.072/90), assinale a alternativa correta.",
    alternativas: ["Admitem fiança, graça e anistia.", "São insuscetíveis de anistia, graça e indulto, e inafiançáveis.", "Têm progressão de regime idêntica aos crimes comuns desde o início.", "Prescrevem em 2 anos.", "São de menor potencial ofensivo."],
    correta: 1,
    explicacao: "Hediondos e equiparados são inafiançáveis e insuscetíveis de anistia, graça e indulto (art. 2º). Correta: B." },
  { id: "leg16", materia: "legislacao", nivel: "facil",
    enunciado: "Disparar arma de fogo em via pública, sem finalidade de atingir alguém, configura, no Estatuto do Desarmamento:",
    alternativas: ["Fato atípico", "Disparo de arma de fogo (art. 15)", "Homicídio tentado", "Porte apenas", "Contravenção"],
    correta: 1,
    explicacao: "É o crime autônomo de DISPARO DE ARMA DE FOGO (art. 15), salvo se o disparo for meio para crime mais grave. Correta: B." },
  { id: "leg17", materia: "legislacao", nivel: "medio",
    enunciado: "A idade a partir da qual, em regra, é possível obter porte de arma (uso permitido), conforme o Estatuto, é:",
    alternativas: ["18 anos", "21 anos", "25 anos", "16 anos", "30 anos"],
    correta: 1,
    explicacao: "O Estatuto exige idade mínima de 25 ANOS para aquisição de arma de fogo por particular (art. 28). Correta: B." },
  { id: "leg18", materia: "legislacao", nivel: "dificil",
    enunciado: "Analise (Lei de Drogas): I. Tráfico é equiparado a hediondo. II. Usuário responde com pena de prisão. III. O tráfico privilegiado reduz a pena. Está(ão) correta(s):",
    alternativas: ["Apenas I", "Apenas I e III", "Apenas II", "Apenas II e III", "I, II e III"],
    correta: 1,
    explicacao: "I e III corretas. II é falsa — o usuário NÃO tem pena de prisão. Correta: B." },
  { id: "leg19", materia: "legislacao", nivel: "medio",
    enunciado: "A corrupção de menores (fazer criança/adolescente participar de crime) é prevista:",
    alternativas: ["No Código de Trânsito", "No ECA (art. 244-B)", "Na Lei de Drogas apenas", "Na Lei de Tortura", "No CDC"],
    correta: 1,
    explicacao: "A corrupção de menores é crime do ECA (art. 244-B), de natureza formal (Súmula 500 STJ). Correta: B." },
  { id: "leg20", materia: "legislacao", nivel: "facil",
    enunciado: "A qual bem jurídico a Lei Maria da Penha visa primordialmente proteger?",
    alternativas: ["O patrimônio público", "A mulher em situação de violência doméstica e familiar", "O meio ambiente", "A ordem tributária", "O consumidor"],
    correta: 1,
    explicacao: "Protege a MULHER em situação de violência doméstica e familiar (art. 1º). Correta: B." },

  /* ===================================================================
     DIREITO CONSTITUCIONAL
     =================================================================== */
  { id: "const1", materia: "constitucional", nivel: "medio",
    enunciado: "Nos termos do art. 144, §5º, da CF/88, às Polícias Militares cabem:",
    alternativas: ["A apuração de infrações penais e polícia judiciária", "A polícia ostensiva e a preservação da ordem pública", "O policiamento de fronteiras e portos", "A guarda de dependências da União", "A administração de presídios"],
    correta: 1,
    explicacao: "Art. 144, §5º: às PM cabem POLÍCIA OSTENSIVA e PRESERVAÇÃO DA ORDEM PÚBLICA. Correta: B." },
  { id: "const2", materia: "constitucional", nivel: "dificil",
    enunciado: "Sobre a liberdade de associação (art. 5º, XIX), é correto afirmar que as associações:",
    alternativas: ["Podem ser dissolvidas por ato do Executivo.", "Só podem ser compulsoriamente dissolvidas por decisão judicial transitada em julgado; a suspensão de atividades basta decisão judicial.", "Nunca podem ser dissolvidas.", "Podem ter atividades suspensas apenas com trânsito em julgado.", "Dependem de autorização estatal para existir."],
    correta: 1,
    explicacao: "DISSOLUÇÃO compulsória exige TRÂNSITO EM JULGADO; SUSPENSÃO basta DECISÃO JUDICIAL. Pegadinha AOCP. Correta: B." },
  { id: "const3", materia: "constitucional", nivel: "medio",
    enunciado: "Sobre os militares dos Estados (art. 42 c/c 142), assinale a correta.",
    alternativas: ["Têm direito a greve e sindicalização.", "São proibidos de sindicalizar-se e de fazer greve.", "Podem candidatar-se sem qualquer condição.", "Não se sujeitam à hierarquia e disciplina.", "Têm estabilidade absoluta."],
    correta: 1,
    explicacao: "Ao militar são VEDADAS greve e sindicalização. Correta: B." },
  { id: "const4", materia: "constitucional", nivel: "medio",
    enunciado: "Tratados de direitos humanos aprovados por 3/5, em 2 turnos, nas duas Casas (art. 5º, §3º) equivalem a:",
    alternativas: ["Leis ordinárias", "Medidas provisórias", "Emendas constitucionais", "Decretos legislativos", "Normas supralegais infraconstitucionais"],
    correta: 2,
    explicacao: "Com o rito do art. 5º, §3º, equivalem a EMENDAS CONSTITUCIONAIS. Correta: C." },
  { id: "const5", materia: "constitucional", nivel: "facil",
    enunciado: "São fundamentos da República (art. 1º), EXCETO:",
    alternativas: ["Soberania", "Cidadania", "Dignidade da pessoa humana", "Prevalência dos direitos humanos", "Pluralismo político"],
    correta: 3,
    explicacao: "Comando EXCETO. 'Prevalência dos direitos humanos' é princípio das RELAÇÕES INTERNACIONAIS (art. 4º), não fundamento do art. 1º. Correta: D." },
  { id: "const6", materia: "constitucional", nivel: "medio",
    enunciado: "São órgãos da segurança pública (art. 144), EXCETO:",
    alternativas: ["Polícia Federal", "Polícia Rodoviária Federal", "Guarda Municipal como polícia judiciária", "Polícias Civis", "Polícias Militares e Corpo de Bombeiros Militar"],
    correta: 2,
    explicacao: "Comando EXCETO. As Guardas Municipais protegem bens/serviços municipais, mas NÃO são polícia judiciária no rol do art. 144. Correta: C." },
  { id: "const7", materia: "constitucional", nivel: "dificil",
    enunciado: "São cláusulas pétreas (art. 60, §4º), EXCETO:",
    alternativas: ["A forma federativa de Estado", "O voto direto, secreto, universal e periódico", "A separação dos Poderes", "Os direitos e garantias individuais", "A gratuidade do transporte público"],
    correta: 4,
    explicacao: "Comando EXCETO. Gratuidade de transporte não é cláusula pétrea. As demais são (art. 60, §4º). Correta: E." },
  { id: "const8", materia: "constitucional", nivel: "medio",
    enunciado: "A CF assegura que ninguém será obrigado a fazer ou deixar de fazer algo senão em virtude de lei. Esse é o princípio da:",
    alternativas: ["Legalidade (art. 5º, II)", "Isonomia", "Moralidade", "Anterioridade", "Publicidade"],
    correta: 0,
    explicacao: "É o princípio da LEGALIDADE (art. 5º, II). Correta: A." },
  { id: "const9", materia: "constitucional", nivel: "medio",
    enunciado: "Sobre o mandado de segurança, é correto afirmar que protege:",
    alternativas: ["Apenas o direito de locomoção", "Direito líquido e certo não amparado por HC ou HD, contra ilegalidade ou abuso de poder de autoridade", "Somente direitos coletivos", "O sigilo de dados exclusivamente", "O direito a certidões apenas"],
    correta: 1,
    explicacao: "MS protege DIREITO LÍQUIDO E CERTO não amparado por habeas corpus ou habeas data (art. 5º, LXIX). Correta: B." },
  { id: "const10", materia: "constitucional", nivel: "facil",
    enunciado: "O habeas corpus tutela:",
    alternativas: ["O direito de propriedade", "A liberdade de locomoção (ir, vir e permanecer)", "O direito à informação", "O sigilo bancário", "A honra"],
    correta: 1,
    explicacao: "HC tutela a LIBERDADE DE LOCOMOÇÃO (art. 5º, LXVIII). Correta: B." },
  { id: "const11", materia: "constitucional", nivel: "dificil",
    enunciado: "Sobre a organização da segurança pública, analise: I. É dever do Estado, direito e responsabilidade de todos. II. É exercida para a preservação da ordem pública e incolumidade das pessoas e do patrimônio. III. As PMs são forças auxiliares e reserva do Exército. Está(ão) correta(s):",
    alternativas: ["Apenas I", "Apenas I e II", "Apenas III", "Apenas II e III", "I, II e III"],
    correta: 4,
    explicacao: "As três estão corretas (art. 144, caput e §6º). Correta: E." },
  { id: "const12", materia: "constitucional", nivel: "medio",
    enunciado: "A idade mínima para o alistamento eleitoral facultativo, segundo a CF, inicia-se aos:",
    alternativas: ["14 anos", "16 anos", "18 anos", "21 anos", "12 anos"],
    correta: 1,
    explicacao: "Voto facultativo aos 16-18 anos, maiores de 70 e analfabetos; obrigatório dos 18 aos 70 (art. 14). Correta: B." },
  { id: "const13", materia: "constitucional", nivel: "medio",
    enunciado: "Em caso de vacância dos cargos de Presidente e Vice nos dois primeiros anos, a CF determina:",
    alternativas: ["Posse definitiva do presidente da Câmara", "Eleição direta em 90 dias após a última vaga", "Continuidade do vice indefinidamente", "Nomeação pelo STF", "Eleição indireta imediata pelo povo"],
    correta: 1,
    explicacao: "Vagando ambos nos 2 primeiros anos: eleição DIRETA em 90 dias (art. 81). Nos 2 últimos, eleição indireta pelo Congresso. Correta: B." },
  { id: "const14", materia: "constitucional", nivel: "facil",
    enunciado: "A prática do racismo, segundo a CF, constitui crime:",
    alternativas: ["Afiançável e prescritível", "Inafiançável e imprescritível, sujeito a reclusão", "De menor potencial ofensivo", "Punível apenas com multa", "Contravenção penal"],
    correta: 1,
    explicacao: "Racismo é crime INAFIANÇÁVEL e IMPRESCRITÍVEL, sujeito à pena de reclusão (art. 5º, XLII). Correta: B." },
  { id: "const15", materia: "constitucional", nivel: "dificil",
    enunciado: "Sobre a administração pública (art. 37), assinale a INCORRETA.",
    alternativas: ["Obedece a legalidade, impessoalidade, moralidade, publicidade e eficiência.", "A investidura em cargo público depende de concurso público, salvo comissionados.", "É vedada a acumulação remunerada de cargos, salvo exceções constitucionais.", "Os cargos em comissão dispensam qualquer critério.", "O prazo de validade do concurso é de até 2 anos, prorrogável uma vez."],
    correta: 3,
    explicacao: "Comando NEGATIVO. Cargos em comissão destinam-se a direção, chefia e assessoramento — não dispensam TODO critério. Correta: D." },
  { id: "const16", materia: "constitucional", nivel: "medio",
    enunciado: "A CF garante a inviolabilidade do domicílio. É possível entrar na casa alheia sem consentimento:",
    alternativas: ["Nunca, em hipótese alguma", "Em caso de flagrante delito, desastre, para prestar socorro, ou, durante o dia, por determinação judicial", "Apenas com mandado, mesmo em flagrante", "Somente à noite", "Apenas com autorização do vizinho"],
    correta: 1,
    explicacao: "Art. 5º, XI: flagrante, desastre, socorro (qualquer hora) ou, DURANTE O DIA, com ordem judicial. Correta: B." },

  /* ===================================================================
     DIREITO ADMINISTRATIVO
     =================================================================== */
  { id: "adm1", materia: "administrativo", nivel: "facil",
    enunciado: "Os princípios expressos da Administração (art. 37, caput) são resumidos na sigla LIMPE. Assinale-os corretamente.",
    alternativas: ["Legalidade, Isonomia, Moralidade, Publicidade, Eficácia", "Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiência", "Liberdade, Impessoalidade, Mérito, Probidade, Economicidade", "Legalidade, Interesse, Motivação, Proporcionalidade, Eficiência", "Legalidade, Impessoalidade, Motivação, Publicidade, Especialidade"],
    correta: 1,
    explicacao: "LIMPE = Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência. Correta: B." },
  { id: "adm2", materia: "administrativo", nivel: "dificil",
    enunciado: "Uma viatura oficial, em serviço, atropela um pedestre. Sobre a responsabilidade civil do Estado:",
    alternativas: ["É subjetiva, exigindo prova de dolo do agente pela vítima.", "É objetiva (risco administrativo), admitindo excludentes como culpa exclusiva da vítima.", "O Estado nunca responde por atos de agentes.", "A vítima deve processar diretamente o motorista.", "É objetiva e integral, sem qualquer excludente."],
    correta: 1,
    explicacao: "Art. 37, §6º: responsabilidade OBJETIVA (risco administrativo) — independe de dolo/culpa, mas admite excludentes. Correta: B." },
  { id: "adm3", materia: "administrativo", nivel: "medio",
    enunciado: "O atributo que permite à Administração executar o ato diretamente, sem ordem judicial prévia, é a:",
    alternativas: ["Presunção de legitimidade", "Imperatividade", "Autoexecutoriedade", "Tipicidade", "Revogabilidade"],
    correta: 2,
    explicacao: "A AUTOEXECUTORIEDADE dispensa a prévia autorização do Judiciário. Correta: C." },
  { id: "adm4", materia: "administrativo", nivel: "medio",
    enunciado: "A Súmula Vinculante 13 do STF trata:",
    alternativas: ["Da greve dos servidores", "Da vedação ao nepotismo", "Do teto remuneratório", "Da acumulação de cargos técnicos", "Da estabilidade"],
    correta: 1,
    explicacao: "A SV 13 veda o NEPOTISMO (nomeação de parentes até 3º grau para comissionados/funções). Correta: B." },
  { id: "adm5", materia: "administrativo", nivel: "facil",
    enunciado: "O poder pelo qual a Administração fiscaliza e restringe direitos individuais em prol do interesse coletivo é o poder:",
    alternativas: ["Hierárquico", "Disciplinar", "De polícia", "Regulamentar", "Vinculado"],
    correta: 2,
    explicacao: "É o PODER DE POLÍCIA — condiciona liberdade e propriedade ao interesse público. Correta: C." },
  { id: "adm6", materia: "administrativo", nivel: "medio",
    enunciado: "A revogação e a anulação do ato administrativo diferem porque:",
    alternativas: ["Ambas decorrem de ilegalidade.", "A anulação atinge ato ILEGAL (efeitos ex tunc); a revogação atinge ato legal inconveniente (efeitos ex nunc).", "A revogação só pode ser feita pelo Judiciário.", "A anulação produz efeitos futuros apenas.", "São sinônimos."],
    correta: 1,
    explicacao: "ANULAÇÃO = ilegalidade, efeitos EX TUNC (retroativos). REVOGAÇÃO = conveniência/oportunidade, ato legal, efeitos EX NUNC. Correta: B." },
  { id: "adm7", materia: "administrativo", nivel: "dificil",
    enunciado: "Sobre a improbidade administrativa (Lei 8.429/92, após a Lei 14.230/21), assinale a correta.",
    alternativas: ["Admite modalidade culposa em todos os tipos.", "Exige, em regra, DOLO para a caracterização dos atos de improbidade.", "Não prevê sanção de perda da função pública.", "É crime, e não ato de improbidade.", "As sanções incluem prisão automática."],
    correta: 1,
    explicacao: "Após a Lei 14.230/21, a improbidade exige DOLO (não há mais modalidade culposa). Correta: B." },
  { id: "adm8", materia: "administrativo", nivel: "medio",
    enunciado: "São requisitos/elementos do ato administrativo:",
    alternativas: ["Competência, finalidade, forma, motivo e objeto", "Apenas forma e objeto", "Somente competência e finalidade", "Dolo, culpa e resultado", "Sujeito, verbo e predicado"],
    correta: 0,
    explicacao: "Elementos: COmpetência, FInalidade, FOrma, MOtivo e Objeto (CO-FI-FO-MO-OB). Correta: A." },
  { id: "adm9", materia: "administrativo", nivel: "facil",
    enunciado: "A administração indireta é composta por:",
    alternativas: ["Ministérios e secretarias", "Autarquias, fundações públicas, empresas públicas e sociedades de economia mista", "Apenas empresas privadas", "Câmara e Senado", "Tribunais"],
    correta: 1,
    explicacao: "Administração INDIRETA: autarquias, fundações, empresas públicas e sociedades de economia mista. Correta: B." },
  { id: "adm10", materia: "administrativo", nivel: "medio",
    enunciado: "O poder de rever os próprios atos, anulando os ilegais e revogando os inconvenientes, é a:",
    alternativas: ["Tutela", "Autotutela", "Hierarquia", "Delegação", "Avocação"],
    correta: 1,
    explicacao: "AUTOTUTELA (Súmulas 346 e 473 do STF): a Administração controla seus próprios atos. Correta: B." },
  { id: "adm11", materia: "administrativo", nivel: "dificil",
    enunciado: "Sobre os poderes administrativos, assinale a INCORRETA.",
    alternativas: ["O poder disciplinar apura infrações e aplica sanções a servidores.", "O poder hierárquico permite dar ordens e rever atos de subordinados.", "O poder de polícia pode ser preventivo ou repressivo.", "O poder regulamentar é privativo do Legislativo.", "O poder vinculado não admite juízo de conveniência."],
    correta: 3,
    explicacao: "Comando NEGATIVO. O poder REGULAMENTAR é do EXECUTIVO (chefe do Executivo edita regulamentos/decretos), não do Legislativo. Correta: D." },
  { id: "adm12", materia: "administrativo", nivel: "medio",
    enunciado: "Configura ato de improbidade que causa PREJUÍZO AO ERÁRIO:",
    alternativas: ["Receber propina (enriquecimento ilícito)", "Frustrar a licitude de processo licitatório, causando perda patrimonial", "Violar princípio da publicidade sem dano", "Deixar de prestar contas (princípios)", "Elogiar um superior"],
    correta: 1,
    explicacao: "Frustrar licitação com perda patrimonial é dano ao erário (art. 10). Propina = enriquecimento (art. 9º). Correta: B." },
  { id: "adm13", materia: "administrativo", nivel: "facil",
    enunciado: "A investidura em cargo público efetivo depende, em regra, de:",
    alternativas: ["Indicação política", "Aprovação prévia em concurso público de provas ou provas e títulos", "Sorteio", "Convite do gestor", "Antiguidade"],
    correta: 1,
    explicacao: "Art. 37, II: cargo efetivo exige CONCURSO PÚBLICO. Correta: B." },
  { id: "adm14", materia: "administrativo", nivel: "medio",
    enunciado: "A delegação de competência administrativa, em regra:",
    alternativas: ["Transfere a titularidade do cargo", "É admitida quando não houver impedimento legal, sendo revogável a qualquer tempo", "É irrevogável", "Só pode ser feita ao subordinado hierárquico direto", "Extingue a competência do delegante"],
    correta: 1,
    explicacao: "A delegação é possível salvo vedação legal e é REVOGÁVEL a qualquer tempo (Lei 9.784/99; Lei estadual GO 13.800/01). Correta: B." },
  { id: "adm15", materia: "administrativo", nivel: "dificil",
    enunciado: "Sobre a responsabilidade civil do Estado por conduta OMISSIVA, prevalece o entendimento de que é, em regra:",
    alternativas: ["Objetiva pura", "Subjetiva (exige demonstração de falta do serviço/culpa)", "Inexistente", "Sempre integral", "Idêntica à comissiva em tudo"],
    correta: 1,
    explicacao: "Para OMISSÃO genérica, prevalece a responsabilidade SUBJETIVA (culpa do serviço). A comissiva é objetiva. Correta: B." },
  { id: "adm16", materia: "administrativo", nivel: "facil",
    enunciado: "O princípio que impede o administrador de perseguir interesses pessoais e exige tratamento igual aos administrados é o da:",
    alternativas: ["Publicidade", "Impessoalidade", "Eficiência", "Motivação", "Continuidade"],
    correta: 1,
    explicacao: "A IMPESSOALIDADE veda favoritismos/perseguições e liga-se à finalidade pública. Correta: B." },

  /* ===================================================================
     DIREITO PENAL
     =================================================================== */
  { id: "pen1", materia: "penal", nivel: "medio",
    enunciado: "Lei penal nova mais benéfica (lex mitior):",
    alternativas: ["Nunca retroage", "Retroage para beneficiar o réu, mesmo após o trânsito em julgado", "Só se aplica a fatos futuros", "Aplica-se só se o réu concordar", "Depende de lei complementar"],
    correta: 1,
    explicacao: "Art. 5º, XL, CF e art. 2º, p.ú., CP: a lei mais benéfica RETROAGE, inclusive após trânsito em julgado. Correta: B." },
  { id: "pen2", materia: "penal", nivel: "facil",
    enunciado: "São excludentes de ILICITUDE (art. 23 CP), EXCETO:",
    alternativas: ["Estado de necessidade", "Legítima defesa", "Estrito cumprimento do dever legal", "Exercício regular de direito", "Coação moral irresistível"],
    correta: 4,
    explicacao: "Comando EXCETO. A coação moral irresistível exclui a CULPABILIDADE (art. 22), não a ilicitude. Correta: E." },
  { id: "pen3", materia: "penal", nivel: "dificil",
    enunciado: "Quando um crime é meio necessário/fase de execução de outro (o maior absorve o menor), aplica-se o princípio da:",
    alternativas: ["Especialidade", "Subsidiariedade", "Consunção (absorção)", "Alternatividade", "Territorialidade"],
    correta: 2,
    explicacao: "CONSUNÇÃO: crime-meio absorvido pelo crime-fim (ex.: Súmula 17 STJ). Correta: C." },
  { id: "pen4", materia: "penal", nivel: "medio",
    enunciado: "O roubo (art. 157) terá a pena aumentada (§2º) em razão de, entre outras hipóteses:",
    alternativas: ["Ser praticado por um só agente", "Concurso de duas ou mais pessoas", "Ausência de violência", "Ser contra pessoa jurídica apenas", "O agente ser primário"],
    correta: 1,
    explicacao: "O §2º majora no CONCURSO DE PESSOAS, restrição da liberdade da vítima etc. (arma de fogo está no §2º-A). Correta: B." },
  { id: "pen5", materia: "penal", nivel: "medio",
    enunciado: "Requisitos da legítima defesa (art. 25 do CP):",
    alternativas: ["Agressão passada e uso desproporcional", "Injusta agressão, atual ou iminente, repelida com uso moderado dos meios necessários, a direito próprio ou alheio", "Qualquer reação a provocação verbal", "Cumprimento de ordem manifestamente ilegal", "Perseguir o agressor após cessada a agressão"],
    correta: 1,
    explicacao: "Legítima defesa: agressão INJUSTA, ATUAL ou IMINENTE; uso MODERADO dos meios NECESSÁRIOS; direito próprio ou alheio. Correta: B." },
  { id: "pen6", materia: "penal", nivel: "facil",
    enunciado: "Quanto ao TEMPO do crime, o CP adota a teoria da:",
    alternativas: ["Ubiquidade", "Atividade (momento da ação/omissão)", "Resultado", "Representação", "Intercorrência"],
    correta: 1,
    explicacao: "TEMPO do crime = teoria da ATIVIDADE (art. 4º). LUGAR = ubiquidade (art. 6º). Correta: B." },
  { id: "pen7", materia: "penal", nivel: "dificil",
    enunciado: "Sobre o iter criminis e a tentativa, assinale a correta.",
    alternativas: ["A cogitação é punível.", "A tentativa ocorre quando, iniciada a execução, o crime não se consuma por circunstâncias alheias à vontade do agente.", "Desistência voluntária e tentativa são a mesma coisa.", "A tentativa tem a mesma pena do crime consumado sempre.", "Atos preparatórios são sempre punidos."],
    correta: 1,
    explicacao: "Tentativa (art. 14, II): execução iniciada, não consumação por circunstâncias ALHEIAS à vontade. Pena reduzida de 1/3 a 2/3. Correta: B." },
  { id: "pen8", materia: "penal", nivel: "medio",
    enunciado: "No estado de necessidade (art. 24), o agente sacrifica bem jurídico para salvar de perigo:",
    alternativas: ["Que ele mesmo causou dolosamente e podia evitar", "Atual, que não provocou por sua vontade e não podia de outro modo evitar, direito próprio ou alheio", "Futuro e incerto", "Já cessado", "Apenas patrimonial da vítima"],
    correta: 1,
    explicacao: "Estado de necessidade: perigo ATUAL, não provocado voluntariamente, inevitável de outro modo, para salvar direito próprio/alheio. Correta: B." },
  { id: "pen9", materia: "penal", nivel: "medio",
    enunciado: "A lei excepcional ou temporária, mesmo após cessada sua vigência, aplica-se ao fato praticado durante sua vigência. Isso é a:",
    alternativas: ["Retroatividade", "Ultratividade", "Abolitio criminis", "Novatio legis in mellius", "Analogia"],
    correta: 1,
    explicacao: "As leis temporárias/excepcionais têm ULTRATIVIDADE (art. 3º): aplicam-se ao fato mesmo depois de revogadas. Correta: B." },
  { id: "pen10", materia: "penal", nivel: "facil",
    enunciado: "O princípio segundo o qual não há crime sem lei anterior que o defina é o da:",
    alternativas: ["Legalidade/anterioridade (reserva legal)", "Insignificância", "Proporcionalidade", "Culpabilidade", "Adequação social"],
    correta: 0,
    explicacao: "Princípio da LEGALIDADE/anterioridade (art. 1º CP; art. 5º, XXXIX, CF): nullum crimen sine lege. Correta: A." },
  { id: "pen11", materia: "penal", nivel: "dificil",
    enunciado: "Analise: I. A lei penal mais grave não retroage. II. Abolitio criminis extingue a punibilidade. III. O tempo do crime segue a teoria do resultado. Está(ão) correta(s):",
    alternativas: ["Apenas I", "Apenas I e II", "Apenas III", "Apenas II e III", "I, II e III"],
    correta: 1,
    explicacao: "I e II corretas. III falsa — TEMPO do crime = teoria da ATIVIDADE. Correta: B." },
  { id: "pen12", materia: "penal", nivel: "medio",
    enunciado: "Subtrair coisa alheia móvel, mediante grave ameaça ou violência à pessoa, configura:",
    alternativas: ["Furto", "Roubo", "Estelionato", "Apropriação indébita", "Extorsão"],
    correta: 1,
    explicacao: "Com violência/grave ameaça = ROUBO (art. 157). Sem violência = furto (art. 155). Correta: B." },
  { id: "pen13", materia: "penal", nivel: "medio",
    enunciado: "A desistência voluntária e o arrependimento eficaz (art. 15) fazem com que o agente responda:",
    alternativas: ["Pelo crime consumado", "Apenas pelos atos já praticados", "Por tentativa", "Por nada", "Em dobro"],
    correta: 1,
    explicacao: "Na desistência voluntária/arrependimento eficaz o agente responde só pelos ATOS JÁ PRATICADOS (tentativa abandonada / ponte de ouro). Correta: B." },
  { id: "pen14", materia: "penal", nivel: "facil",
    enunciado: "Matar alguém é crime de:",
    alternativas: ["Lesão corporal", "Homicídio (art. 121)", "Ameaça", "Constrangimento ilegal", "Perigo de vida"],
    correta: 1,
    explicacao: "Matar alguém = HOMICÍDIO (art. 121 do CP). Correta: B." },
  { id: "pen15", materia: "penal", nivel: "dificil",
    enunciado: "Sobre a aberratio ictus (erro na execução), assinale a correta.",
    alternativas: ["O agente é absolvido sempre.", "Responde como se tivesse atingido a vítima pretendida (consideram-se as condições da vítima virtual).", "Configura sempre crime culposo.", "Exclui o dolo.", "Torna o fato atípico."],
    correta: 1,
    explicacao: "Na aberratio ictus (art. 73), o agente responde considerando as qualidades da vítima PRETENDIDA. Correta: B." },
  { id: "pen16", materia: "penal", nivel: "medio",
    enunciado: "O agente que, por erro plenamente justificado, supõe situação de fato que tornaria a ação legítima, incorre em:",
    alternativas: ["Erro de proibição direto", "Descriminante putativa (art. 20, §1º)", "Crime doloso comum", "Coação irresistível", "Caso fortuito"],
    correta: 1,
    explicacao: "Supor situação de fato que, se existisse, legitimaria a conduta = DESCRIMINANTE PUTATIVA (art. 20, §1º). Correta: B." },

  /* ===================================================================
     DIREITO PROCESSUAL PENAL
     =================================================================== */
  { id: "pp1", materia: "proc_penal", nivel: "medio",
    enunciado: "A prisão TEMPORÁRIA (Lei 7.960/89), para crimes comuns, tem prazo de:",
    alternativas: ["24 horas improrrogável", "5 dias, prorrogável por mais 5 em caso de extrema necessidade", "10 dias improrrogável", "30 dias, prorrogável por mais 30", "90 dias"],
    correta: 1,
    explicacao: "Regra: 5 + 5 dias. Em HEDIONDOS: 30 + 30. Correta: B." },
  { id: "pp2", materia: "proc_penal", nivel: "dificil",
    enunciado: "A autoridade policial pode arbitrar FIANÇA quando a infração tiver pena privativa máxima:",
    alternativas: ["Não superior a 2 anos", "Não superior a 4 anos", "Superior a 4 anos", "De qualquer quantidade", "Apenas em contravenções"],
    correta: 1,
    explicacao: "Art. 322 CPP: o delegado arbitra fiança quando a pena máxima NÃO for superior a 4 ANOS. Correta: B." },
  { id: "pp3", materia: "proc_penal", nivel: "medio",
    enunciado: "A prisão PREVENTIVA (art. 312) pode fundar-se em, EXCETO:",
    alternativas: ["Garantia da ordem pública", "Garantia da ordem econômica", "Conveniência da instrução criminal", "Assegurar a aplicação da lei penal", "Antecipação automática da pena"],
    correta: 4,
    explicacao: "Comando EXCETO. A preventiva JAMAIS é antecipação de pena (presunção de inocência). Correta: E." },
  { id: "pp4", materia: "proc_penal", nivel: "facil",
    enunciado: "O inquérito policial tem natureza:",
    alternativas: ["Jurisdicional e contraditória", "Administrativa, inquisitiva e preparatória", "Executória", "Recursal", "Legislativa"],
    correta: 1,
    explicacao: "O IP é procedimento ADMINISTRATIVO, INQUISITIVO e PREPARATÓRIO da ação penal. Correta: B." },
  { id: "pp5", materia: "proc_penal", nivel: "medio",
    enunciado: "A audiência de custódia deve ocorrer, em regra, no prazo de:",
    alternativas: ["48 horas", "24 horas da prisão", "72 horas", "5 dias", "10 dias"],
    correta: 1,
    explicacao: "O preso é apresentado ao juiz em até 24 HORAS (art. 310 CPP). Correta: B." },
  { id: "pp6", materia: "proc_penal", nivel: "medio",
    enunciado: "São espécies de prisão cautelar, EXCETO:",
    alternativas: ["Prisão em flagrante", "Prisão preventiva", "Prisão temporária", "Prisão-pena (definitiva após trânsito em julgado)", "Todas são cautelares"],
    correta: 3,
    explicacao: "Comando EXCETO. A prisão-pena (definitiva) NÃO é cautelar — decorre de condenação transitada em julgado. Correta: D." },
  { id: "pp7", materia: "proc_penal", nivel: "dificil",
    enunciado: "Sobre o flagrante, o flagrante 'esperado' (a autoridade aguarda a prática do crime que já iria ocorrer) é considerado:",
    alternativas: ["Flagrante forjado (crime)", "Flagrante preparado (nulo, Súmula 145 STF)", "Flagrante esperado, válido", "Flagrante impossível", "Prisão ilegal sempre"],
    correta: 2,
    explicacao: "O flagrante ESPERADO é VÁLIDO (não há indução/provocação). O PREPARADO é nulo (Súmula 145). Correta: C." },
  { id: "pp8", materia: "proc_penal", nivel: "facil",
    enunciado: "O habeas corpus, no processo penal, é cabível para:",
    alternativas: ["Proteger a honra", "Sanar ilegalidade ou abuso que ameace ou viole a liberdade de locomoção", "Discutir mérito de dívida", "Garantir informações pessoais", "Anular contrato"],
    correta: 1,
    explicacao: "HC tutela a LIBERDADE DE LOCOMOÇÃO contra coação ilegal (art. 5º, LXVIII, CF; art. 647 CPP). Correta: B." },
  { id: "pp9", materia: "proc_penal", nivel: "medio",
    enunciado: "Ninguém será considerado culpado até o trânsito em julgado de sentença penal condenatória. Esse é o princípio da:",
    alternativas: ["Ampla defesa", "Presunção de inocência (não culpabilidade)", "Duplo grau", "Publicidade", "Oralidade"],
    correta: 1,
    explicacao: "É a PRESUNÇÃO DE INOCÊNCIA / não culpabilidade (art. 5º, LVII, CF). Correta: B." },
  { id: "pp10", materia: "proc_penal", nivel: "dificil",
    enunciado: "Sobre a prisão em flagrante, assinale a INCORRETA.",
    alternativas: ["Considera-se em flagrante quem é surpreendido cometendo o crime.", "Também quem acaba de cometê-lo.", "Quem é perseguido logo após, em situação que faça presumir autoria.", "Qualquer pessoa pode prender quem está em flagrante.", "O flagrante só pode ser dado pela autoridade policial."],
    correta: 4,
    explicacao: "Comando NEGATIVO. QUALQUER pessoa pode prender em flagrante (flagrante facultativo); a autoridade e agentes DEVEM (obrigatório). Correta: E." },
  { id: "pp11", materia: "proc_penal", nivel: "medio",
    enunciado: "Recebida a notícia de crime de ação pública incondicionada, a autoridade policial deve, em regra:",
    alternativas: ["Aguardar autorização judicial para investigar", "Instaurar inquérito policial de ofício", "Pedir representação da vítima sempre", "Arquivar imediatamente", "Comunicar apenas ao MP e nada fazer"],
    correta: 1,
    explicacao: "Em ação pública INCONDICIONADA, o delegado instaura IP DE OFÍCIO (art. 5º, I, CPP). Correta: B." },
  { id: "pp12", materia: "proc_penal", nivel: "facil",
    enunciado: "O prazo do inquérito policial, estando o indiciado PRESO (crime comum), é, em regra, de:",
    alternativas: ["5 dias", "10 dias", "15 dias", "30 dias", "60 dias"],
    correta: 1,
    explicacao: "IP com indiciado PRESO: 10 dias; SOLTO: 30 dias (prorrogável) — art. 10 CPP. Correta: B." },

  /* ===================================================================
     LÍNGUA PORTUGUESA
     =================================================================== */
  { id: "pt1", materia: "portugues", nivel: "medio",
    enunciado: "Em 'Precisa-se de policiais dedicados', a palavra 'se' é:",
    alternativas: ["Pronome apassivador", "Índice de indeterminação do sujeito", "Conjunção integrante", "Conjunção condicional", "Pronome reflexivo"],
    correta: 1,
    explicacao: "Com VTI ('precisar de'), o 'se' é ÍNDICE DE INDETERMINAÇÃO DO SUJEITO (verbo no singular). Correta: B." },
  { id: "pt2", materia: "portugues", nivel: "facil",
    enunciado: "Assinale a alternativa em que a crase está CORRETA.",
    alternativas: ["Refiro-me à pessoas de bem.", "Cheguei à Brasília na segunda.", "Entreguei o relatório à comandante da unidade.", "Ele começou à trabalhar cedo.", "Vou à qualquer lugar."],
    correta: 2,
    explicacao: "Crase = prep. 'a' + artigo 'a'. 'à comandante' tem os dois. Não há crase antes de plural sem artigo, verbo, 'Brasília' (sem artigo) ou pronome indefinido. Correta: C." },
  { id: "pt3", materia: "portugues", nivel: "medio",
    enunciado: "Sobre a Redação Oficial, assinale o atributo que NÃO a caracteriza.",
    alternativas: ["Impessoalidade", "Clareza e concisão", "Formalidade e padronização", "Linguagem rebuscada e pessoal", "Uso do padrão culto"],
    correta: 3,
    explicacao: "Comando NEGATIVO. A redação oficial NÃO é rebuscada nem pessoal. Correta: D." },
  { id: "pt4", materia: "portugues", nivel: "medio",
    enunciado: "Em 'O policial permaneceu atento durante o patrulhamento', 'atento' é:",
    alternativas: ["Objeto direto", "Predicativo do sujeito", "Adjunto adverbial", "Complemento nominal", "Aposto"],
    correta: 1,
    explicacao: "'Permanecer' é verbo de ligação; 'atento' é PREDICATIVO DO SUJEITO. Correta: B." },
  { id: "pt5", materia: "portugues", nivel: "medio",
    enunciado: "Assinale a frase com concordância verbal CORRETA.",
    alternativas: ["Fazem dois anos que ingressei.", "Houveram muitos aprovados.", "Faz dois anos que ingressei na corporação.", "Existe muitos problemas.", "Deve haver menos de dez candidatos, mas devem existir vagas."],
    correta: 2,
    explicacao: "'Fazer' (tempo) e 'haver' (existir) são IMPESSOAIS, ficam no singular: 'Faz dois anos'. Correta: C." },
  { id: "pt6", materia: "portugues", nivel: "dificil",
    enunciado: "Em 'Espero que todos SE esforcem', o 'se' classifica-se como:",
    alternativas: ["Conjunção integrante", "Parte integrante do verbo (pronominal: esforçar-se)", "Índice de indeterminação do sujeito", "Pronome apassivador", "Conjunção condicional"],
    correta: 1,
    explicacao: "'Esforçar-se' é verbo pronominal; o 'se' é PARTE INTEGRANTE DO VERBO. Correta: B." },
  { id: "pt7", materia: "portugues", nivel: "medio",
    enunciado: "A colocação pronominal correta em frase iniciada por palavra atrativa aparece em:",
    alternativas: ["Não vi-o ontem.", "Não o vi ontem.", "Nunca dir-lhe-ei isso com 'não'.", "Me chamaram cedo (início de frase).", "Que diga-se a verdade."],
    correta: 1,
    explicacao: "Palavra negativa 'não' ATRAI o pronome (próclise): 'Não o vi'. Correta: B." },
  { id: "pt8", materia: "portugues", nivel: "facil",
    enunciado: "Em 'Comprei livros, cadernos e canetas', as vírgulas separam:",
    alternativas: ["Orações coordenadas", "Elementos de mesma função sintática em enumeração", "Aposto explicativo", "Vocativo", "Oração subordinada"],
    correta: 1,
    explicacao: "As vírgulas separam ELEMENTOS EM ENUMERAÇÃO (mesma função). Correta: B." },
  { id: "pt9", materia: "portugues", nivel: "medio",
    enunciado: "A oração destacada em 'Estudou muito PARA QUE FOSSE APROVADO' exprime ideia de:",
    alternativas: ["Causa", "Finalidade", "Condição", "Concessão", "Tempo"],
    correta: 1,
    explicacao: "'Para que' introduz oração subordinada adverbial FINAL (finalidade). Correta: B." },
  { id: "pt10", materia: "portugues", nivel: "dificil",
    enunciado: "Em 'EMBORA estivesse cansado, seguiu no patrulhamento', a conjunção 'embora' indica:",
    alternativas: ["Causa", "Concessão", "Conclusão", "Adição", "Alternância"],
    correta: 1,
    explicacao: "'Embora' é conjunção CONCESSIVA (admite um obstáculo que não impede o fato). Correta: B." },
  { id: "pt11", materia: "portugues", nivel: "medio",
    enunciado: "Assinale a alternativa com regência verbal CORRETA (norma padrão).",
    alternativas: ["Assisti o filme ontem (ver).", "Assisti ao filme ontem.", "Cheguei na delegacia.", "Prefiro estudar do que trabalhar.", "Namoro com ela."],
    correta: 1,
    explicacao: "'Assistir' (ver/presenciar) é VTI, exige 'a': 'assisti AO filme'. 'Chegar' pede 'a' (cheguei À delegacia). Correta: B." },
  { id: "pt12", materia: "portugues", nivel: "facil",
    enunciado: "O 'que' em 'Este é o livro QUE comprei' funciona como:",
    alternativas: ["Conjunção integrante", "Pronome relativo", "Advérbio", "Interjeição", "Preposição"],
    correta: 1,
    explicacao: "'Que' retoma 'o livro' e liga orações: PRONOME RELATIVO. Correta: B." },
  { id: "pt13", materia: "portugues", nivel: "medio",
    enunciado: "Em 'Ele agiu de modo covarde', o termo 'covarde' modifica um advérbio implícito e classifica-se como:",
    alternativas: ["Substantivo", "Adjetivo com valor adverbial / adjunto adnominal de 'modo'", "Verbo", "Pronome", "Conjunção"],
    correta: 1,
    explicacao: "'Covarde' caracteriza 'modo' — adjetivo (adjunto adnominal) com valor de circunstância. Correta: B." },
  { id: "pt14", materia: "portugues", nivel: "dificil",
    enunciado: "Assinale a reescrita que MANTÉM o sentido e a correção de 'O soldado, que era corajoso, avançou'.",
    alternativas: ["O soldado que era corajoso avançou (restritiva, muda o sentido).", "Corajoso, o soldado avançou.", "O soldado avançou porque era covarde.", "Avançou o soldado, mas não era corajoso.", "O soldado talvez avançasse se fosse corajoso."],
    correta: 1,
    explicacao: "A oração é explicativa (entre vírgulas). 'Corajoso, o soldado avançou' preserva sentido e correção. Correta: B." },
  { id: "pt15", materia: "portugues", nivel: "medio",
    enunciado: "Em 'Choveu muito; portanto, o TAF foi adiado', o conectivo 'portanto' exprime:",
    alternativas: ["Adição", "Conclusão", "Oposição", "Explicação", "Condição"],
    correta: 1,
    explicacao: "'Portanto' é conjunção coordenativa CONCLUSIVA. Correta: B." },
  { id: "pt16", materia: "portugues", nivel: "facil",
    enunciado: "O plural de 'cidadão' é:",
    alternativas: ["cidadões", "cidadãos", "cidadães", "cidadans", "cidadãoes"],
    correta: 1,
    explicacao: "O plural de 'cidadão' é CIDADÃOS. Correta: B." },
];
